<?php

namespace Database\Seeders;

use App\Models\Patient;
use App\Models\User;
use Illuminate\Database\Seeder;

class PatientSeeder extends Seeder
{
    public function run()
    {
        $patients = [
            // Existing Patients
            [
                'email' => 'tasneem.m.g11@gmail.com',
                'emergency_contact' => '+201100000001',
                'insurance_provider' => 'Health Insurance Company',
                'insurance_policy_number' => 'INS123456',
                'insurance_info' => 'Health Insurance Company - Policy No: INS123456',
                'medical_history' => 'No significant medical history',
                'blood_type' => 'O+',
                'allergies' => 'None',
                'chronic_conditions' => 'None',
            ],
            [
                'email' => 'eslam@booking.com',
                'emergency_contact' => '+201100000002',
                'insurance_provider' => 'Medical Care Insurance',
                'insurance_policy_number' => 'INS789012',
                'insurance_info' => 'Medical Care Insurance - Policy No: INS789012',
                'medical_history' => 'Allergic to penicillin',
                'blood_type' => 'A+',
                'allergies' => 'Penicillin, Dust mites',
                'chronic_conditions' => 'Mild asthma',
            ],
            [
                'email' => 'mariam.ibrahim@booking.com',
                'emergency_contact' => '+201100000003',
                'insurance_provider' => 'National Health Insurance',
                'insurance_policy_number' => 'INS234567',
                'insurance_info' => 'National Health Insurance - Policy No: INS234567',
                'medical_history' => 'Previous appendectomy in 2018',
                'blood_type' => 'B+',
                'allergies' => 'Shellfish',
                'chronic_conditions' => 'None',
            ],
            [
                'email' => 'youssef.mahmoud@booking.com',
                'emergency_contact' => '+201100000004',
                'insurance_provider' => 'Premium Health Care',
                'insurance_policy_number' => 'INS345678',
                'insurance_info' => 'Premium Health Care - Policy No: INS345678',
                'medical_history' => 'Hypertension diagnosed in 2020',
                'blood_type' => 'AB+',
                'allergies' => 'None',
                'chronic_conditions' => 'Hypertension',
            ],
            [
                'email' => 'nour.eldin@booking.com',
                'emergency_contact' => '+201100000005',
                'insurance_provider' => 'Family Health Plan',
                'insurance_policy_number' => 'INS456789',
                'insurance_info' => 'Family Health Plan - Policy No: INS456789',
                'medical_history' => 'Type 2 Diabetes, managed with medication',
                'blood_type' => 'O-',
                'allergies' => 'Latex',
                'chronic_conditions' => 'Type 2 Diabetes',
            ],
            [
                'email' => 'fatma.mohamed@booking.com',
                'emergency_contact' => '+201100000006',
                'insurance_provider' => 'Comprehensive Care',
                'insurance_policy_number' => 'INS567890',
                'insurance_info' => 'Comprehensive Care - Policy No: INS567890',
                'medical_history' => 'Seasonal allergies, migraines',
                'blood_type' => 'A-',
                'allergies' => 'Pollen, Pet dander',
                'chronic_conditions' => 'Migraine headaches',
            ],
            [
                'email' => 'karim.abdelrahman@booking.com',
                'emergency_contact' => '+201100000007',
                'insurance_provider' => 'Health Shield',
                'insurance_policy_number' => 'INS678901',
                'insurance_info' => 'Health Shield - Policy No: INS678901',
                'medical_history' => 'Sports injury - knee surgery in 2019',
                'blood_type' => 'B-',
                'allergies' => 'Ibuprofen',
                'chronic_conditions' => 'None',
            ],
            [
                'email' => 'layla.ahmed@booking.com',
                'emergency_contact' => '+201100000008',
                'insurance_provider' => 'Wellness Plus',
                'insurance_policy_number' => 'INS789012',
                'insurance_info' => 'Wellness Plus - Policy No: INS789012',
                'medical_history' => 'Anemia, regular iron supplements',
                'blood_type' => 'O+',
                'allergies' => 'None',
                'chronic_conditions' => 'Iron deficiency anemia',
            ],
            [
                'email' => 'amr.mostafa@booking.com',
                'emergency_contact' => '+201100000009',
                'insurance_provider' => 'Prime Medical',
                'insurance_policy_number' => 'INS890123',
                'insurance_info' => 'Prime Medical - Policy No: INS890123',
                'medical_history' => 'High cholesterol, on statin medication',
                'blood_type' => 'A+',
                'allergies' => 'None',
                'chronic_conditions' => 'Hyperlipidemia',
            ],
            [
                'email' => 'dina.samir@booking.com',
                'emergency_contact' => '+201100000010',
                'insurance_provider' => 'Care First',
                'insurance_policy_number' => 'INS901234',
                'insurance_info' => 'Care First - Policy No: INS901234',
                'medical_history' => 'Thyroid condition, regular monitoring',
                'blood_type' => 'B+',
                'allergies' => 'Sulfa drugs',
                'chronic_conditions' => 'Hypothyroidism',
            ],
            [
                'email' => 'hassan.farouk@booking.com',
                'emergency_contact' => '+201100000011',
                'insurance_provider' => 'Health Guard',
                'insurance_policy_number' => 'INS012345',
                'insurance_info' => 'Health Guard - Policy No: INS012345',
                'medical_history' => 'No significant medical history',
                'blood_type' => 'AB-',
                'allergies' => 'None',
                'chronic_conditions' => 'None',
            ],
            [
                'email' => 'rana.tarek@booking.com',
                'emergency_contact' => '+201100000012',
                'insurance_provider' => 'Total Health',
                'insurance_policy_number' => 'INS123789',
                'insurance_info' => 'Total Health - Policy No: INS123789',
                'medical_history' => 'PCOS, managed with lifestyle and medication',
                'blood_type' => 'O+',
                'allergies' => 'None',
                'chronic_conditions' => 'Polycystic Ovary Syndrome (PCOS)',
            ],
            // Additional Patients
            [
                'email' => 'ahmed.hassan.patient@booking.com',
                'emergency_contact' => '+201100000050',
                'insurance_provider' => 'Global Health Insurance',
                'insurance_policy_number' => 'INS500001',
                'insurance_info' => 'Global Health Insurance - Policy No: INS500001',
                'medical_history' => 'No significant medical history',
                'blood_type' => 'A+',
                'allergies' => 'None',
                'chronic_conditions' => 'None',
            ],
            [
                'email' => 'sara.mahmoud.patient@booking.com',
                'emergency_contact' => '+201100000051',
                'insurance_provider' => 'Medicare Plus',
                'insurance_policy_number' => 'INS500002',
                'insurance_info' => 'Medicare Plus - Policy No: INS500002',
                'medical_history' => 'Mild depression, managed with therapy',
                'blood_type' => 'O-',
                'allergies' => 'None',
                'chronic_conditions' => 'Mild depression',
            ],
            [
                'email' => 'mohamed.ali.patient@booking.com',
                'emergency_contact' => '+201100000052',
                'insurance_provider' => 'Health First',
                'insurance_policy_number' => 'INS500003',
                'insurance_info' => 'Health First - Policy No: INS500003',
                'medical_history' => 'Back pain from old injury',
                'blood_type' => 'B+',
                'allergies' => 'Codeine',
                'chronic_conditions' => 'Chronic back pain',
            ],
            [
                'email' => 'amina.hassan.patient@booking.com',
                'emergency_contact' => '+201100000053',
                'insurance_provider' => 'Care Network',
                'insurance_policy_number' => 'INS500004',
                'insurance_info' => 'Care Network - Policy No: INS500004',
                'medical_history' => 'Gestational diabetes during pregnancy',
                'blood_type' => 'AB+',
                'allergies' => 'None',
                'chronic_conditions' => 'None',
            ],
            [
                'email' => 'omar.mahmoud.patient@booking.com',
                'emergency_contact' => '+201100000054',
                'insurance_provider' => 'Prime Care',
                'insurance_policy_number' => 'INS500005',
                'insurance_info' => 'Prime Care - Policy No: INS500005',
                'medical_history' => 'Acid reflux, on medication',
                'blood_type' => 'A-',
                'allergies' => 'None',
                'chronic_conditions' => 'GERD',
            ],
            [
                'email' => 'laila.ahmed.patient@booking.com',
                'emergency_contact' => '+201100000055',
                'insurance_provider' => 'Wellness Care',
                'insurance_policy_number' => 'INS500006',
                'insurance_info' => 'Wellness Care - Policy No: INS500006',
                'medical_history' => 'No significant medical history',
                'blood_type' => 'O+',
                'allergies' => 'None',
                'chronic_conditions' => 'None',
            ],
            [
                'email' => 'hassan.ibrahim.patient@booking.com',
                'emergency_contact' => '+201100000056',
                'insurance_provider' => 'Medical Guard',
                'insurance_policy_number' => 'INS500007',
                'insurance_info' => 'Medical Guard - Policy No: INS500007',
                'medical_history' => 'Previous tonsillectomy',
                'blood_type' => 'B-',
                'allergies' => 'None',
                'chronic_conditions' => 'None',
            ],
            [
                'email' => 'nadia.mostafa.patient@booking.com',
                'emergency_contact' => '+201100000057',
                'insurance_provider' => 'Health Alliance',
                'insurance_policy_number' => 'INS500008',
                'insurance_info' => 'Health Alliance - Policy No: INS500008',
                'medical_history' => 'Irregular periods, under investigation',
                'blood_type' => 'AB-',
                'allergies' => 'None',
                'chronic_conditions' => 'None',
            ],
            [
                'email' => 'tarek.hassan.patient@booking.com',
                'emergency_contact' => '+201100000058',
                'insurance_provider' => 'Complete Care',
                'insurance_policy_number' => 'INS500009',
                'insurance_info' => 'Complete Care - Policy No: INS500009',
                'medical_history' => 'No significant medical history',
                'blood_type' => 'A+',
                'allergies' => 'None',
                'chronic_conditions' => 'None',
            ],
            [
                'email' => 'mona.ali.patient@booking.com',
                'emergency_contact' => '+201100000059',
                'insurance_provider' => 'MediCare Solutions',
                'insurance_policy_number' => 'INS500010',
                'insurance_info' => 'MediCare Solutions - Policy No: INS500010',
                'medical_history' => 'Vitamin D deficiency',
                'blood_type' => 'O-',
                'allergies' => 'None',
                'chronic_conditions' => 'Vitamin D deficiency',
            ],
            [
                'email' => 'khaled.mahmoud.patient@booking.com',
                'emergency_contact' => '+201100000060',
                'insurance_provider' => 'Health Partners',
                'insurance_policy_number' => 'INS500011',
                'insurance_info' => 'Health Partners - Policy No: INS500011',
                'medical_history' => 'Occasional migraines',
                'blood_type' => 'B+',
                'allergies' => 'None',
                'chronic_conditions' => 'Migraine headaches',
            ],
            [
                'email' => 'reem.hassan.patient@booking.com',
                'emergency_contact' => '+201100000061',
                'insurance_provider' => 'Care Plus',
                'insurance_policy_number' => 'INS500012',
                'insurance_info' => 'Care Plus - Policy No: INS500012',
                'medical_history' => 'No significant medical history',
                'blood_type' => 'A-',
                'allergies' => 'None',
                'chronic_conditions' => 'None',
            ],
            [
                'email' => 'wael.ahmed.patient@booking.com',
                'emergency_contact' => '+201100000062',
                'insurance_provider' => 'Medical Network',
                'insurance_policy_number' => 'INS500013',
                'insurance_info' => 'Medical Network - Policy No: INS500013',
                'medical_history' => 'Previous ankle fracture',
                'blood_type' => 'AB+',
                'allergies' => 'None',
                'chronic_conditions' => 'None',
            ],
            [
                'email' => 'salma.mostafa.patient@booking.com',
                'emergency_contact' => '+201100000063',
                'insurance_provider' => 'Health Shield Plus',
                'insurance_policy_number' => 'INS500014',
                'insurance_info' => 'Health Shield Plus - Policy No: INS500014',
                'medical_history' => 'Seasonal allergies',
                'blood_type' => 'O+',
                'allergies' => 'Pollen',
                'chronic_conditions' => 'Seasonal allergies',
            ],
            [
                'email' => 'ali.ibrahim.patient@booking.com',
                'emergency_contact' => '+201100000064',
                'insurance_provider' => 'Total Health Care',
                'insurance_policy_number' => 'INS500015',
                'insurance_info' => 'Total Health Care - Policy No: INS500015',
                'medical_history' => 'No significant medical history',
                'blood_type' => 'B-',
                'allergies' => 'None',
                'chronic_conditions' => 'None',
            ],
            [
                'email' => 'hana.mahmoud.patient@booking.com',
                'emergency_contact' => '+201100000065',
                'insurance_provider' => 'Wellness Network',
                'insurance_policy_number' => 'INS500016',
                'insurance_info' => 'Wellness Network - Policy No: INS500016',
                'medical_history' => 'Anxiety, managed with therapy',
                'blood_type' => 'A+',
                'allergies' => 'None',
                'chronic_conditions' => 'Generalized anxiety',
            ],
            [
                'email' => 'samir.hassan.patient@booking.com',
                'emergency_contact' => '+201100000066',
                'insurance_provider' => 'Prime Health',
                'insurance_policy_number' => 'INS500017',
                'insurance_info' => 'Prime Health - Policy No: INS500017',
                'medical_history' => 'High blood pressure, well controlled',
                'blood_type' => 'O-',
                'allergies' => 'None',
                'chronic_conditions' => 'Hypertension',
            ],
            [
                'email' => 'nora.ali.patient@booking.com',
                'emergency_contact' => '+201100000067',
                'insurance_provider' => 'Care Alliance',
                'insurance_policy_number' => 'INS500018',
                'insurance_info' => 'Care Alliance - Policy No: INS500018',
                'medical_history' => 'No significant medical history',
                'blood_type' => 'AB-',
                'allergies' => 'None',
                'chronic_conditions' => 'None',
            ],
            [
                'email' => 'yasser.mahmoud.patient@booking.com',
                'emergency_contact' => '+201100000068',
                'insurance_provider' => 'Medical Partners',
                'insurance_policy_number' => 'INS500019',
                'insurance_info' => 'Medical Partners - Policy No: INS500019',
                'medical_history' => 'Previous gallbladder surgery',
                'blood_type' => 'B+',
                'allergies' => 'None',
                'chronic_conditions' => 'None',
            ],
            [
                'email' => 'farida.hassan.patient@booking.com',
                'emergency_contact' => '+201100000069',
                'insurance_provider' => 'Health Solutions',
                'insurance_policy_number' => 'INS500020',
                'insurance_info' => 'Health Solutions - Policy No: INS500020',
                'medical_history' => 'Fibromyalgia, managed with medication',
                'blood_type' => 'A-',
                'allergies' => 'None',
                'chronic_conditions' => 'Fibromyalgia',
            ],
            [
                'email' => 'ziad.ahmed.patient@booking.com',
                'emergency_contact' => '+201100000070',
                'insurance_provider' => 'Complete Health',
                'insurance_policy_number' => 'INS500021',
                'insurance_info' => 'Complete Health - Policy No: INS500021',
                'medical_history' => 'No significant medical history',
                'blood_type' => 'O+',
                'allergies' => 'None',
                'chronic_conditions' => 'None',
            ],
            [
                'email' => 'samar.mostafa.patient@booking.com',
                'emergency_contact' => '+201100000071',
                'insurance_provider' => 'MediCare Network',
                'insurance_policy_number' => 'INS500022',
                'insurance_info' => 'MediCare Network - Policy No: INS500022',
                'medical_history' => 'Asthma, mild and well controlled',
                'blood_type' => 'AB+',
                'allergies' => 'Dust',
                'chronic_conditions' => 'Mild asthma',
            ],
            [
                'email' => 'ibrahim.hassan.patient@booking.com',
                'emergency_contact' => '+201100000072',
                'insurance_provider' => 'Health Guardians',
                'insurance_policy_number' => 'INS500023',
                'insurance_info' => 'Health Guardians - Policy No: INS500023',
                'medical_history' => 'No significant medical history',
                'blood_type' => 'B-',
                'allergies' => 'None',
                'chronic_conditions' => 'None',
            ],
            [
                'email' => 'lobna.mahmoud.patient@booking.com',
                'emergency_contact' => '+201100000073',
                'insurance_provider' => 'Care Providers',
                'insurance_policy_number' => 'INS500024',
                'insurance_info' => 'Care Providers - Policy No: INS500024',
                'medical_history' => 'Endometriosis, managed with medication',
                'blood_type' => 'A+',
                'allergies' => 'None',
                'chronic_conditions' => 'Endometriosis',
            ],
            [
                'email' => 'fady.ali.patient@booking.com',
                'emergency_contact' => '+201100000074',
                'insurance_provider' => 'Medical Excellence',
                'insurance_policy_number' => 'INS500025',
                'insurance_info' => 'Medical Excellence - Policy No: INS500025',
                'medical_history' => 'No significant medical history',
                'blood_type' => 'O-',
                'allergies' => 'None',
                'chronic_conditions' => 'None',
            ],
            [
                'email' => 'rania.hassan.patient@booking.com',
                'emergency_contact' => '+201100000075',
                'insurance_provider' => 'Wellness Partners',
                'insurance_policy_number' => 'INS500026',
                'insurance_info' => 'Wellness Partners - Policy No: INS500026',
                'medical_history' => 'Postpartum depression, resolved',
                'blood_type' => 'B+',
                'allergies' => 'None',
                'chronic_conditions' => 'None',
            ],
            [
                'email' => 'sherif.mahmoud.patient@booking.com',
                'emergency_contact' => '+201100000076',
                'insurance_provider' => 'Health Network Plus',
                'insurance_policy_number' => 'INS500027',
                'insurance_info' => 'Health Network Plus - Policy No: INS500027',
                'medical_history' => 'No significant medical history',
                'blood_type' => 'AB-',
                'allergies' => 'None',
                'chronic_conditions' => 'None',
            ],
            [
                'email' => 'maha.ahmed.patient@booking.com',
                'emergency_contact' => '+201100000077',
                'insurance_provider' => 'Prime Medical Plus',
                'insurance_policy_number' => 'INS500028',
                'insurance_info' => 'Prime Medical Plus - Policy No: INS500028',
                'medical_history' => 'Chronic sinusitis',
                'blood_type' => 'A-',
                'allergies' => 'None',
                'chronic_conditions' => 'Chronic sinusitis',
            ],
            [
                'email' => 'gamal.mostafa.patient@booking.com',
                'emergency_contact' => '+201100000078',
                'insurance_provider' => 'Care Excellence',
                'insurance_policy_number' => 'INS500029',
                'insurance_info' => 'Care Excellence - Policy No: INS500029',
                'medical_history' => 'Previous hernia surgery',
                'blood_type' => 'O+',
                'allergies' => 'None',
                'chronic_conditions' => 'None',
            ],
            [
                'email' => 'heba.hassan.patient@booking.com',
                'emergency_contact' => '+201100000079',
                'insurance_provider' => 'Medical Alliance',
                'insurance_policy_number' => 'INS500030',
                'insurance_info' => 'Medical Alliance - Policy No: INS500030',
                'medical_history' => 'No significant medical history',
                'blood_type' => 'B-',
                'allergies' => 'None',
                'chronic_conditions' => 'None',
            ],
            [
                'email' => 'tamer.mahmoud.patient@booking.com',
                'emergency_contact' => '+201100000080',
                'insurance_provider' => 'Health Providers',
                'insurance_policy_number' => 'INS500031',
                'insurance_info' => 'Health Providers - Policy No: INS500031',
                'medical_history' => 'Recurring urinary tract infections',
                'blood_type' => 'AB+',
                'allergies' => 'None',
                'chronic_conditions' => 'Recurring UTIs',
            ],
            [
                'email' => 'soha.ali.patient@booking.com',
                'emergency_contact' => '+201100000081',
                'insurance_provider' => 'Complete Wellness',
                'insurance_policy_number' => 'INS500032',
                'insurance_info' => 'Complete Wellness - Policy No: INS500032',
                'medical_history' => 'No significant medical history',
                'blood_type' => 'A+',
                'allergies' => 'None',
                'chronic_conditions' => 'None',
            ],
            [
                'email' => 'maged.hassan.patient@booking.com',
                'emergency_contact' => '+201100000082',
                'insurance_provider' => 'MediCare Partners',
                'insurance_policy_number' => 'INS500033',
                'insurance_info' => 'MediCare Partners - Policy No: INS500033',
                'medical_history' => 'Previous kidney stones',
                'blood_type' => 'O-',
                'allergies' => 'None',
                'chronic_conditions' => 'None',
            ],
            [
                'email' => 'yasmin.mahmoud.patient@booking.com',
                'emergency_contact' => '+201100000083',
                'insurance_provider' => 'Health Solutions Plus',
                'insurance_policy_number' => 'INS500034',
                'insurance_info' => 'Health Solutions Plus - Policy No: INS500034',
                'medical_history' => 'No significant medical history',
                'blood_type' => 'B+',
                'allergies' => 'None',
                'chronic_conditions' => 'None',
            ],
            [
                'email' => 'hesham.ahmed.patient@booking.com',
                'emergency_contact' => '+201100000084',
                'insurance_provider' => 'Care Network Plus',
                'insurance_policy_number' => 'INS500035',
                'insurance_info' => 'Care Network Plus - Policy No: INS500035',
                'medical_history' => 'Mild sleep apnea',
                'blood_type' => 'A-',
                'allergies' => 'None',
                'chronic_conditions' => 'Mild sleep apnea',
            ],
            [
                'email' => 'nermin.mostafa.patient@booking.com',
                'emergency_contact' => '+201100000085',
                'insurance_provider' => 'Medical Network Plus',
                'insurance_policy_number' => 'INS500036',
                'insurance_info' => 'Medical Network Plus - Policy No: INS500036',
                'medical_history' => 'Osteoarthritis in knees',
                'blood_type' => 'AB-',
                'allergies' => 'None',
                'chronic_conditions' => 'Osteoarthritis',
            ],
            [
                'email' => 'ramadan.hassan.patient@booking.com',
                'emergency_contact' => '+201100000086',
                'insurance_provider' => 'Prime Care Plus',
                'insurance_policy_number' => 'INS500037',
                'insurance_info' => 'Prime Care Plus - Policy No: INS500037',
                'medical_history' => 'No significant medical history',
                'blood_type' => 'O+',
                'allergies' => 'None',
                'chronic_conditions' => 'None',
            ],
            [
                'email' => 'wedad.mahmoud.patient@booking.com',
                'emergency_contact' => '+201100000087',
                'insurance_provider' => 'Wellness Alliance',
                'insurance_policy_number' => 'INS500038',
                'insurance_info' => 'Wellness Alliance - Policy No: INS500038',
                'medical_history' => 'Borderline high cholesterol',
                'blood_type' => 'B-',
                'allergies' => 'None',
                'chronic_conditions' => 'Borderline hyperlipidemia',
            ],
        ];

        foreach ($patients as $patientData) {
            $user = User::where('email', $patientData['email'])->first();
            if ($user) {
                Patient::create([
                    'user_id' => $user->id,
                    'emergency_contact' => $patientData['emergency_contact'],
                    'insurance_provider' => $patientData['insurance_provider'],
                    'insurance_policy_number' => $patientData['insurance_policy_number'],
                    'insurance_info' => $patientData['insurance_info'],
                    'medical_history' => $patientData['medical_history'],
                    'blood_type' => $patientData['blood_type'],
                    'allergies' => $patientData['allergies'],
                    'chronic_conditions' => $patientData['chronic_conditions'],
                ]);
            }
        }
    }
}
