<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run()
    {
        // Admin User
        User::create([
            'name' => 'System Admin',
            'email' => 'tasneemgaballah16@gmail.com',
            'password' => Hash::make('password'),
            'role' => 'admin',
            'phone' => '+201000000001',
            'date_of_birth' => '1980-01-01',
            'address' => 'Cairo, Egypt',
        ]);

        // Doctor Users (30 total: 7 existing + 23 new)
        $doctors = [
            // Existing Doctors
            [
                'name' => 'Dr. Ahmed Taha',
                'email' => 'ahmed185taha@Gmail.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000002',
                'date_of_birth' => '1985-05-15',
                'address' => 'Alexandria, Egypt',
            ],
            [
                'name' => 'Dr. Aya Basheer',
                'email' => 'doctor2@booking.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000003',
                'date_of_birth' => '1988-08-20',
                'address' => 'Giza, Egypt',
            ],
            [
                'name' => 'Dr. Tasneem Gaballah',
                'email' => 'tasneemgaballah11@gmail.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000006',
                'date_of_birth' => '1990-03-12',
                'address' => 'Cairo, Egypt',
            ],
            [
                'name' => 'Dr. Islam Ghanem',
                'email' => 'islam.ghanem@booking.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000010',
                'date_of_birth' => '1991-04-20',
                'address' => 'Tanta, Egypt',
            ],
            [
                'name' => 'Dr. Mohamed Hassan',
                'email' => 'mohamed.hassan@booking.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000007',
                'date_of_birth' => '1987-11-25',
                'address' => 'Zagazig, Egypt',
            ],
            [
                'name' => 'Dr. Sara Ali',
                'email' => 'sara.ali@booking.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000008',
                'date_of_birth' => '1992-06-18',
                'address' => 'Ismailia, Egypt',
            ],
            [
                'name' => 'Dr. Omar Khaled',
                'email' => 'omar.khaled@booking.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000009',
                'date_of_birth' => '1989-09-30',
                'address' => 'Port Said, Egypt',
            ],
            // Additional Cardiology Doctors (Specialization 1)
            [
                'name' => 'Dr. Mahmoud Ibrahim',
                'email' => 'mahmoud.ibrahim@booking.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000020',
                'date_of_birth' => '1983-07-12',
                'address' => 'Cairo, Egypt',
            ],
            [
                'name' => 'Dr. Nour El-Din Hassan',
                'email' => 'nour.hassan@booking.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000021',
                'date_of_birth' => '1986-09-28',
                'address' => 'Alexandria, Egypt',
            ],
            // Additional Dermatology Doctors (Specialization 2)
            [
                'name' => 'Dr. Salma Mahmoud',
                'email' => 'salma.mahmoud@booking.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000022',
                'date_of_birth' => '1989-11-15',
                'address' => 'Giza, Egypt',
            ],
            [
                'name' => 'Dr. Tamer Hassan',
                'email' => 'tamer.hassan@booking.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000023',
                'date_of_birth' => '1987-03-22',
                'address' => 'Cairo, Egypt',
            ],
            // Additional Neurology Doctors (Specialization 3)
            [
                'name' => 'Dr. Reem Ahmed',
                'email' => 'reem.ahmed@booking.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000024',
                'date_of_birth' => '1990-05-08',
                'address' => 'Alexandria, Egypt',
            ],
            [
                'name' => 'Dr. Khaled Mostafa',
                'email' => 'khaled.mostafa@booking.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000025',
                'date_of_birth' => '1984-12-30',
                'address' => 'Tanta, Egypt',
            ],
            // Additional Pediatrics Doctors (Specialization 4)
            [
                'name' => 'Dr. Hana Ali',
                'email' => 'hana.ali@booking.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000026',
                'date_of_birth' => '1991-08-14',
                'address' => 'Zagazig, Egypt',
            ],
            [
                'name' => 'Dr. Wael Mahmoud',
                'email' => 'wael.mahmoud@booking.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000027',
                'date_of_birth' => '1988-01-17',
                'address' => 'Ismailia, Egypt',
            ],
            // Additional Orthopedics Doctors (Specialization 5)
            [
                'name' => 'Dr. Mona Ibrahim',
                'email' => 'mona.ibrahim@booking.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000028',
                'date_of_birth' => '1985-04-25',
                'address' => 'Port Said, Egypt',
            ],
            [
                'name' => 'Dr. Hassan Ali',
                'email' => 'hassan.ali@booking.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000029',
                'date_of_birth' => '1982-06-10',
                'address' => 'Cairo, Egypt',
            ],
            // Additional Gynecology Doctors (Specialization 6)
            [
                'name' => 'Dr. Laila Mahmoud',
                'email' => 'laila.mahmoud@booking.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000030',
                'date_of_birth' => '1987-10-03',
                'address' => 'Alexandria, Egypt',
            ],
            [
                'name' => 'Dr. Amira Hassan',
                'email' => 'amira.hassan@booking.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000031',
                'date_of_birth' => '1993-02-19',
                'address' => 'Giza, Egypt',
            ],
            // Additional Dentistry Doctors (Specialization 7)
            [
                'name' => 'Dr. Youssef Ahmed',
                'email' => 'youssef.ahmed@booking.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000032',
                'date_of_birth' => '1986-07-05',
                'address' => 'Tanta, Egypt',
            ],
            [
                'name' => 'Dr. Dina Mostafa',
                'email' => 'dina.mostafa@booking.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000033',
                'date_of_birth' => '1992-11-12',
                'address' => 'Zagazig, Egypt',
            ],
            // Psychiatry Doctors (Specialization 8)
            [
                'name' => 'Dr. Ahmed Mostafa',
                'email' => 'ahmed.mostafa@booking.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000034',
                'date_of_birth' => '1984-03-08',
                'address' => 'Cairo, Egypt',
            ],
            [
                'name' => 'Dr. Fatma Hassan',
                'email' => 'fatma.hassan@booking.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000035',
                'date_of_birth' => '1989-09-21',
                'address' => 'Alexandria, Egypt',
            ],
            [
                'name' => 'Dr. Kareem Ali',
                'email' => 'kareem.ali@booking.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000036',
                'date_of_birth' => '1990-12-14',
                'address' => 'Giza, Egypt',
            ],
            // Ophthalmology Doctors (Specialization 9)
            [
                'name' => 'Dr. Samira Mahmoud',
                'email' => 'samira.mahmoud@booking.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000037',
                'date_of_birth' => '1985-06-27',
                'address' => 'Tanta, Egypt',
            ],
            [
                'name' => 'Dr. Omar Ibrahim',
                'email' => 'omar.ibrahim@booking.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000038',
                'date_of_birth' => '1988-08-09',
                'address' => 'Port Said, Egypt',
            ],
            [
                'name' => 'Dr. Nour Ahmed',
                'email' => 'nour.ahmed@booking.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000039',
                'date_of_birth' => '1991-01-30',
                'address' => 'Ismailia, Egypt',
            ],
            // General Practice Doctors (Specialization 10)
            [
                'name' => 'Dr. Mohamed Ali',
                'email' => 'mohamed.ali@booking.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000040',
                'date_of_birth' => '1983-04-16',
                'address' => 'Cairo, Egypt',
            ],
            [
                'name' => 'Dr. Amina Hassan',
                'email' => 'amina.hassan@booking.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000041',
                'date_of_birth' => '1987-11-23',
                'address' => 'Alexandria, Egypt',
            ],
            [
                'name' => 'Dr. Tarek Mahmoud',
                'email' => 'tarek.mahmoud@booking.com',
                'password' => Hash::make('password'),
                'role' => 'doctor',
                'phone' => '+201000000042',
                'date_of_birth' => '1989-05-07',
                'address' => 'Giza, Egypt',
            ],
        ];

        foreach ($doctors as $doctor) {
            User::create($doctor);
        }

        // Patient Users (50 total: 12 existing + 38 new)
        $patients = [
            // Existing Patients
            [
                'name' => 'Patient Test User',
                'email' => 'tasneem.m.g11@gmail.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000004',
                'date_of_birth' => '1995-03-10',
                'address' => 'Mansoura, Egypt',
            ],
            [
                'name' => 'Eslam Ghanem',
                'email' => 'eslam@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000005',
                'date_of_birth' => '1998-07-22',
                'address' => 'Tanta, Egypt',
            ],
            [
                'name' => 'Mariam Ibrahim',
                'email' => 'mariam.ibrahim@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000010',
                'date_of_birth' => '1996-04-15',
                'address' => 'Cairo, Egypt',
            ],
            [
                'name' => 'Youssef Mahmoud',
                'email' => 'youssef.mahmoud@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000011',
                'date_of_birth' => '1993-08-20',
                'address' => 'Alexandria, Egypt',
            ],
            [
                'name' => 'Nour El-Din',
                'email' => 'nour.eldin@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000012',
                'date_of_birth' => '1997-12-05',
                'address' => 'Giza, Egypt',
            ],
            [
                'name' => 'Fatma Mohamed',
                'email' => 'fatma.mohamed@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000013',
                'date_of_birth' => '1994-02-28',
                'address' => 'Mansoura, Egypt',
            ],
            [
                'name' => 'Karim Abdelrahman',
                'email' => 'karim.abdelrahman@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000014',
                'date_of_birth' => '1999-10-14',
                'address' => 'Tanta, Egypt',
            ],
            [
                'name' => 'Layla Ahmed',
                'email' => 'layla.ahmed@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000015',
                'date_of_birth' => '1995-07-08',
                'address' => 'Cairo, Egypt',
            ],
            [
                'name' => 'Amr Mostafa',
                'email' => 'amr.mostafa@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000016',
                'date_of_birth' => '1992-11-22',
                'address' => 'Alexandria, Egypt',
            ],
            [
                'name' => 'Dina Samir',
                'email' => 'dina.samir@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000017',
                'date_of_birth' => '1996-05-30',
                'address' => 'Giza, Egypt',
            ],
            [
                'name' => 'Hassan Farouk',
                'email' => 'hassan.farouk@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000018',
                'date_of_birth' => '1991-09-17',
                'address' => 'Zagazig, Egypt',
            ],
            [
                'name' => 'Rana Tarek',
                'email' => 'rana.tarek@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000019',
                'date_of_birth' => '1998-01-25',
                'address' => 'Ismailia, Egypt',
            ],
            // Additional Patients
            [
                'name' => 'Ahmed Hassan',
                'email' => 'ahmed.hassan.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000050',
                'date_of_birth' => '1988-06-12',
                'address' => 'Cairo, Egypt',
            ],
            [
                'name' => 'Sara Mahmoud',
                'email' => 'sara.mahmoud.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000051',
                'date_of_birth' => '1994-09-18',
                'address' => 'Alexandria, Egypt',
            ],
            [
                'name' => 'Mohamed Ali',
                'email' => 'mohamed.ali.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000052',
                'date_of_birth' => '1990-11-25',
                'address' => 'Giza, Egypt',
            ],
            [
                'name' => 'Amina Hassan',
                'email' => 'amina.hassan.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000053',
                'date_of_birth' => '1996-03-07',
                'address' => 'Tanta, Egypt',
            ],
            [
                'name' => 'Omar Mahmoud',
                'email' => 'omar.mahmoud.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000054',
                'date_of_birth' => '1992-07-14',
                'address' => 'Mansoura, Egypt',
            ],
            [
                'name' => 'Laila Ahmed',
                'email' => 'laila.ahmed.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000055',
                'date_of_birth' => '1997-12-03',
                'address' => 'Zagazig, Egypt',
            ],
            [
                'name' => 'Hassan Ibrahim',
                'email' => 'hassan.ibrahim.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000056',
                'date_of_birth' => '1989-04-22',
                'address' => 'Ismailia, Egypt',
            ],
            [
                'name' => 'Nadia Mostafa',
                'email' => 'nadia.mostafa.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000057',
                'date_of_birth' => '1993-08-09',
                'address' => 'Port Said, Egypt',
            ],
            [
                'name' => 'Tarek Hassan',
                'email' => 'tarek.hassan.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000058',
                'date_of_birth' => '1995-01-16',
                'address' => 'Cairo, Egypt',
            ],
            [
                'name' => 'Mona Ali',
                'email' => 'mona.ali.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000059',
                'date_of_birth' => '1991-05-28',
                'address' => 'Alexandria, Egypt',
            ],
            [
                'name' => 'Khaled Mahmoud',
                'email' => 'khaled.mahmoud.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000060',
                'date_of_birth' => '1987-10-11',
                'address' => 'Giza, Egypt',
            ],
            [
                'name' => 'Reem Hassan',
                'email' => 'reem.hassan.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000061',
                'date_of_birth' => '1998-02-19',
                'address' => 'Tanta, Egypt',
            ],
            [
                'name' => 'Wael Ahmed',
                'email' => 'wael.ahmed.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000062',
                'date_of_birth' => '1994-06-30',
                'address' => 'Mansoura, Egypt',
            ],
            [
                'name' => 'Salma Mostafa',
                'email' => 'salma.mostafa.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000063',
                'date_of_birth' => '1996-11-08',
                'address' => 'Zagazig, Egypt',
            ],
            [
                'name' => 'Ali Ibrahim',
                'email' => 'ali.ibrahim.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000064',
                'date_of_birth' => '1990-12-24',
                'address' => 'Ismailia, Egypt',
            ],
            [
                'name' => 'Hana Mahmoud',
                'email' => 'hana.mahmoud.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000065',
                'date_of_birth' => '1997-04-05',
                'address' => 'Port Said, Egypt',
            ],
            [
                'name' => 'Samir Hassan',
                'email' => 'samir.hassan.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000066',
                'date_of_birth' => '1986-08-17',
                'address' => 'Cairo, Egypt',
            ],
            [
                'name' => 'Nora Ali',
                'email' => 'nora.ali.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000067',
                'date_of_birth' => '1993-09-29',
                'address' => 'Alexandria, Egypt',
            ],
            [
                'name' => 'Yasser Mahmoud',
                'email' => 'yasser.mahmoud.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000068',
                'date_of_birth' => '1989-01-13',
                'address' => 'Giza, Egypt',
            ],
            [
                'name' => 'Farida Hassan',
                'email' => 'farida.hassan.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000069',
                'date_of_birth' => '1995-07-21',
                'address' => 'Tanta, Egypt',
            ],
            [
                'name' => 'Ziad Ahmed',
                'email' => 'ziad.ahmed.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000070',
                'date_of_birth' => '1992-03-04',
                'address' => 'Mansoura, Egypt',
            ],
            [
                'name' => 'Samar Mostafa',
                'email' => 'samar.mostafa.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000071',
                'date_of_birth' => '1998-05-26',
                'address' => 'Zagazig, Egypt',
            ],
            [
                'name' => 'Ibrahim Hassan',
                'email' => 'ibrahim.hassan.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000072',
                'date_of_birth' => '1987-11-09',
                'address' => 'Ismailia, Egypt',
            ],
            [
                'name' => 'Lobna Mahmoud',
                'email' => 'lobna.mahmoud.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000073',
                'date_of_birth' => '1994-12-31',
                'address' => 'Port Said, Egypt',
            ],
            [
                'name' => 'Fady Ali',
                'email' => 'fady.ali.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000074',
                'date_of_birth' => '1991-06-15',
                'address' => 'Cairo, Egypt',
            ],
            [
                'name' => 'Rania Hassan',
                'email' => 'rania.hassan.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000075',
                'date_of_birth' => '1996-10-02',
                'address' => 'Alexandria, Egypt',
            ],
            [
                'name' => 'Sherif Mahmoud',
                'email' => 'sherif.mahmoud.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000076',
                'date_of_birth' => '1988-02-27',
                'address' => 'Giza, Egypt',
            ],
            [
                'name' => 'Maha Ahmed',
                'email' => 'maha.ahmed.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000077',
                'date_of_birth' => '1997-08-23',
                'address' => 'Tanta, Egypt',
            ],
            [
                'name' => 'Gamal Mostafa',
                'email' => 'gamal.mostafa.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000078',
                'date_of_birth' => '1985-04-06',
                'address' => 'Mansoura, Egypt',
            ],
            [
                'name' => 'Heba Hassan',
                'email' => 'heba.hassan.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000079',
                'date_of_birth' => '1993-09-14',
                'address' => 'Zagazig, Egypt',
            ],
            [
                'name' => 'Tamer Mahmoud',
                'email' => 'tamer.mahmoud.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000080',
                'date_of_birth' => '1990-01-08',
                'address' => 'Ismailia, Egypt',
            ],
            [
                'name' => 'Soha Ali',
                'email' => 'soha.ali.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000081',
                'date_of_birth' => '1999-03-20',
                'address' => 'Port Said, Egypt',
            ],
            [
                'name' => 'Maged Hassan',
                'email' => 'maged.hassan.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000082',
                'date_of_birth' => '1986-07-12',
                'address' => 'Cairo, Egypt',
            ],
            [
                'name' => 'Yasmin Mahmoud',
                'email' => 'yasmin.mahmoud.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000083',
                'date_of_birth' => '1995-11-18',
                'address' => 'Alexandria, Egypt',
            ],
            [
                'name' => 'Hesham Ahmed',
                'email' => 'hesham.ahmed.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000084',
                'date_of_birth' => '1989-05-25',
                'address' => 'Giza, Egypt',
            ],
            [
                'name' => 'Nermin Mostafa',
                'email' => 'nermin.mostafa.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000085',
                'date_of_birth' => '1994-10-07',
                'address' => 'Tanta, Egypt',
            ],
            [
                'name' => 'Ramadan Hassan',
                'email' => 'ramadan.hassan.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000086',
                'date_of_birth' => '1991-12-29',
                'address' => 'Mansoura, Egypt',
            ],
            [
                'name' => 'Wedad Mahmoud',
                'email' => 'wedad.mahmoud.patient@booking.com',
                'password' => Hash::make('password'),
                'role' => 'patient',
                'phone' => '+201000000087',
                'date_of_birth' => '1997-06-03',
                'address' => 'Zagazig, Egypt',
            ],
        ];

        foreach ($patients as $patient) {
            User::create($patient);
        }
    }
}
